### ISSUE TITLE
Measure wrong register in jupyter-notebook division

### ISSUE THREAD

**Issue by Fergus-Hayes** [LM095/QuantumDeskCalculator#1]
Hi,

This is a very nice bit of software that demonstrates basic arithmetic operations very nicely. 

I just want to point out that the jupyter-notebook division example measures the 'b' register and not the 'accumulator' register and so gets the wrong answer. This is not a problem in your python script implementation.

Fergus

**Comment by DebbyX3** [comment]
> Hi,
> 
> This is a very nice bit of software that demonstrates basic arithmetic operations very nicely.
> 
> I just want to point out that the jupyter-notebook division example measures the 'b' register and not the 'accumulator' register and so gets the wrong answer. This is not a problem in your python script implementation.
> 
> Fergus

Hi Fergus,
thank you very much! I'll fix the bug shortly

So sorry for the late reply - this was a university project, so we didn't keep an eye on this repository after completing the course.
